use anyhow::Result;
use rusqlite::Connection;

use crate::app::generation::generate_tour_narrative;
use crate::app::memory::query_memories;
use crate::app::topology::compute_topology;
use crate::runtime_config::GenerationConfig;

pub(crate) fn generate_onboarding_guide(
    conn: &Connection,
    gen_config: &GenerationConfig,
) -> Result<String> {
    let mut lines = Vec::new();

    lines.push("# Project Onboarding Guide".to_string());
    lines.push("\n> Welcome to the project! This guide was automatically generated from the local knowledge graph (dukememory).\n".to_string());

    // 1. Architecture Layers
    let architecture_nodes = query_memories(
        conn,
        None,
        &["architecture".to_string()],
        &["active".to_string()],
        None,
        20,
    )?;

    if !architecture_nodes.is_empty() {
        lines.push("## Architecture".to_string());
        lines.push(
            "\nThe project is organized into the following architectural layers or components:\n"
                .to_string(),
        );
        for node in architecture_nodes {
            lines.push(format!("### {}", node.title));
            lines.push(format!("{}\n", node.body));
        }
    }

    // 2. Key Concepts & Goals
    let mut concept_nodes = query_memories(
        conn,
        None,
        &["concept".to_string(), "product_goal".to_string()],
        &["active".to_string()],
        None,
        20,
    )?;

    // Also include top decisions
    let mut decisions = query_memories(
        conn,
        None,
        &["decision".to_string()],
        &["active".to_string()],
        None,
        5,
    )?;
    concept_nodes.append(&mut decisions);

    if !concept_nodes.is_empty() {
        lines.push("## Key Concepts & Decisions".to_string());
        lines.push(
            "\nImportant domain concepts, product goals, and active decisions to understand:\n"
                .to_string(),
        );
        for node in concept_nodes {
            lines.push(format!("### {} ({})", node.title, node.memory_type));
            lines.push(format!("{}\n", node.body));
        }
    }

    // 3. Getting Started (Tour)
    lines.push("## Getting Started".to_string());
    lines.push("\nGenerating guided tour of the codebase...\n".to_string());

    match compute_topology(conn) {
        Ok(topology) => match generate_tour_narrative(gen_config, &topology) {
            Ok(narrative) => {
                lines.push(narrative);
            }
            Err(err) => {
                lines.push(format!("> Failed to generate LLM tour: {}", err));
            }
        },
        Err(err) => {
            lines.push(format!("> Failed to compute graph topology: {}", err));
        }
    }

    // 4. Important Files (Hotspots)
    // We fetch some files that might be important (e.g. recent or frequently linked)
    let file_nodes = query_memories(
        conn,
        None,
        &["file".to_string()],
        &["active".to_string()],
        None,
        15,
    )?;

    if !file_nodes.is_empty() {
        lines.push("\n## File Map (Hotspots)".to_string());
        lines.push("\n| Component | Summary |".to_string());
        lines.push("|-----------|---------|".to_string());
        for node in file_nodes {
            let summary = node
                .body
                .lines()
                .next()
                .unwrap_or("")
                .chars()
                .take(80)
                .collect::<String>();
            lines.push(format!("| `{}` | {}... |", node.title, summary));
        }
    }

    lines.push("\n---".to_string());
    lines.push("\n*Generated by dukememory from the local knowledge graph*".to_string());

    Ok(lines.join("\n"))
}
